---
- name: "Deploy maven artifact"
  maven_artifact:
    group_id:       "{{ phillyapp_group_id }}"
    artifact_id:    "{{ phillyapp_artifact_id }}"
    extension:      "{{ phillyapp_extension }}"
    repository_url: "{{ phillyapp_repository_url }}"
    version:        "{{ phillyapp_version }}"
    dest:           "{{ phillyapp_dir }}/{{ phillyapp_artifact_id }}.{{ phillyapp_extension }}"

- name: "waiting Playbook"
  pause:
    seconds: 10

- name: "GET webpage content from application"
  uri:
    url: "http://localhost:8080/{{ phillyapp_artifact_id }}/"
    return_content: yes
  register: webpage
